micronaut:
  application:
    name: partycipate
  security:
    authentication: session
    redirect:
      login-success: /
      login-failure: /login/authFailed
    oauth2:
      clients:
        default:
          client-id: user
          client-secret: password
datasources:
  default:
    url: jdbc:mysql://pma.tutorialfactory.org/partycipate
    driverClassName: com.mysql.cj.jdbc.Driver
    username: partycipate
    password: '99GRcY40mIzYRZkc'
endpoints:
  health:
    details-visible: anonymous