micronaut:
  application:
    name: partycipate
datasources:
  default:
    connectionFactoryClassName: oracle.jdbc.pool.OracleDataSource
    url: jdbc:mysql://pma.tutorialfactory.org
    driverClassName: com.mysql.cj.jdbc.Driver
    username: partycipate
    password: '99GRcY40mIzYRZkc'
    maxActiveConnections: 10
endpoints:
  all:
    enabled: true
  health:
    details-visible: anonymous
