micronaut:
  application:
    name: partycipate
  security:
    authentication: session
    oauth2:
      clients:
        default:
          client-id: ${OAUTH_CLIENT_ID}
          client-secret: ${OAUTH_CLIENT_SECRET}
datasources:
  default:
    url: jdbc:mysql://pma.tutorialfactory.org/partycipate
    driverClassName: com.mysql.cj.jdbc.Driver
    username: partycipate
    password: '99GRcY40mIzYRZkc'
